# Generated by Django 4.2.7 on 2023-11-23 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Choices",
            new_name="Choice",
        ),
    ]
