# Generated by Django 4.2.7 on 2023-11-23 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_rename_choices_choice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="choices_text",
            new_name="choice_text",
        ),
    ]
